### ISSUE TITLE
Python 3.6 support

### ISSUE THREAD

**Issue by arlt** [phsmith/rundeck_exporter#55]
with 2.4.11 we get the following error messages:

```
Traceback (most recent call last):
File "/opt/rundeck_exporter-2.4.11/rundeck_exporter.py", line 488, in <module>
RundeckMetricsCollector.run()
File "/opt/rundeck_exporter-2.4.11/rundeck_exporter.py", line 475, in run
REGISTRY.register(RundeckMetricsCollector())
File "/opt/rundeck_exporter-2.4.11/rundeck_exporter.py", line 157, in __init__
defaults=[1, 2, 3]
TypeError: namedtuple() got an unexpected keyword argument 'defaults'
```

Seems like the `namedtuple` change came with version 2.4.9 and needs Python 3.7.

In enterprise os like RHEL 7 (support until 2024/06), Phyton 3.6 is still supported.

Would it be possible for you to support Phyton 3.6?

**Comment by phsmith** [comment]
Working on it @arlt !

**Comment by phsmith** [comment]
Just published release [v2.4.12](/phsmith/rundeck_exporter/releases/tag/v2.4.12) that should work with Python 3.6.

Please, report on any problems.

**Comment by arlt** [comment]
Works - perfect. Thanks!
